---

- name: Install Prerequisite Packages
  apt:
    name: gnupg
    state: present

- name: Add Mono Apt Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add Mono Repository
  apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-bionic main
    state: present
    filename: mono-official-stable

- name: Add Sonarr Apt Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8

- name: Add Sonarr v3 Repository
  apt_repository:
    repo: deb https://apt.sonarr.tv/ubuntu bionic main
    state: present
    filename: sonarr

- name: Update System
  apt:
    update_cache: true
    upgrade: full

- name: Install Sonarr
  apt:
    name: sonarr

- name: sonarr config
  template:
    src: config.xml
    dest: /var/lib/sonarr/config.xml
    owner: sonarr
    group: sonarr
    mode: 0644
  become: true
  notify: restart sonarr
